version: '3'
services:
  postgres:
    image: postgres:11.6
    volumes:
      - video-uploader-postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
  web:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
      - ~/.aws:/root/.aws
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  q_cluster:
    restart: always
    environment:
      - DJANGO_SECRET_KEY=local
    build: ./
    command: >
      bash -c "python wait_for_postgres.py &&
              ./manage.py migrate &&
               ./manage.py qcluster"
    volumes:
      - ./:/code
      - ~/.aws:/root/.aws
    depends_on:
      - web
  documentation:
    restart: always
    build: ./
    command: "mkdocs serve"
    volumes:
      - ./:/code
    ports:
      - "8001:8001"

volumes:
  video-uploader-postgres-data: