site_name: video-uploader
site_description: Video Upload an
repo_url: https://github.com/anuragregmi/video-uploader-backend
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/anuragregmi">anuragregmi</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
    - Videos: 'api/videos.md'
