# Generated by Django 3.2.5 on 2021-08-07 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_remove_video_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='converted_path',
        ),
        migrations.AddField(
            model_name='video',
            name='outputs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='transcoder_job_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='video',
            name='raw_file',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'wmv', 'webm'])]),
        ),
    ]
