# Generated by Django 3.2.5 on 2021-08-08 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_video_trancode_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='trancode_status',
            new_name='transcode_status',
        ),
    ]
